eureka:
    client:
        registry-fetch-interval-seconds: 10
        serviceUrl:
            defaultZone: http://bbg:bbg1234@10.12.29.240:31025/eureka
    instance:
        lease-expiration-duration-in-seconds: 20
        lease-renewal-interval-in-seconds: 5
        prefer-ip-address: true
logging:
    file: ./logs/shelvesTentManager.log
    level:
        com:
            bbg:
                mapper: debug

mybatis-plus:
    configuration:
        map-underscore-to-camel-case: true
    global-config:
        db-column-underline: true
        field-strategy: 2
        id-type: 0
    mapper-locations: classpath:mappers/*.xml
    typeAliasesPackage: com.bbg.pojo
server:
    port: 8282
    
#spring:
#    application:
#        name: serviceApi
#    datasource:
#        driverClassName: oracle.jdbc.driver.OracleDriver
#        password: zfl
#        type: com.alibaba.druid.pool.DruidDataSource
#        url: jdbc:oracle:thin:@192.168.5.14:1521:crmolap
#        username: zfl
        
        
spring:
  datasource:
    dynamic:
      primary: oracle #记得设置一个默认数据源
      datasource:
        mysql:
           driverClassName: com.mysql.jdbc.Driver
           password: root
          
           url: jdbc:mysql://localhost:3306/bbg_inventory?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false
           username: root
           druid: #以下均为默认值
             initial-size: 3
             max-active: 8
             min-idle: 2
             max-wait: -1
             min-evictable-idle-time-millis: 30000
             max-evictable-idle-time-millis: 30000
             time-between-eviction-runs-millis: 0
             validation-query: select 1
             validation-query-timeout: -1
             test-on-borrow: false
             test-on-return: false
             test-while-idle: true
             pool-prepared-statements: true
             max-open-prepared-statements: 100
             filters: stat,wall
             share-prepared-statements: true
        oracle:
           driverClassName: oracle.jdbc.driver.OracleDriver
           password: zfl
           url: jdbc:oracle:thin:@192.168.5.14:1521:crmolap
           username: zfl
           druid: #以下均为默认值
             initial-size: 3
             max-active: 8
             min-idle: 2
             max-wait: -1
             min-evictable-idle-time-millis: 30000
             max-evictable-idle-time-millis: 30000
             time-between-eviction-runs-millis: 0
             validation-query: select 1 from dual
             validation-query-timeout: -1
             test-on-borrow: false
             test-on-return: false
             test-while-idle: true
             pool-prepared-statements: true
             max-open-prepared-statements: 100
             filters: stat,wall
             share-prepared-statements: true
       